Make sure that documents with Cyrillic name are displayed correctly in both webdav on nautilus and web navigator.
exodev/jcr pull request #69
Opened 2020-11-09 13:08 UTC by mdiha

2020-11-09 17:53 UTC, ahamdi requested changes
Please do not change signatures and instead craete a separate function that tries to decode the value and in case of catching UnsupportedEncodingException return the node.getName()

2020-11-10 11:08 UTC, mdiha commented
> Please do not change signatures and instead craete a separate function that tries to decode the value and in case of catching UnsupportedEncodingException return the node.getName()

Done.

2020-11-10 16:27 UTC, ahamdi requested changes

2020-11-10 16:28 UTC, ahamdi commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/GenericResource.java
> +      String currentValue;
Is there a reason to not use URLDecoder.decode() twice?

2020-11-10 17:00 UTC, mdiha commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/GenericResource.java
> +      String currentValue;
Yes since we don't know how many times the string has been encoded.

2020-11-10 17:01 UTC, mdiha commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/xml/PropstatGroupedRepresentation.java
> +import javax.jcr.*;
Okay.

2020-11-10 17:25 UTC, ahamdi reviewed
This PR is proposed on develop, copuld you rebase it on feature/maintenance

2020-11-11 11:45 UTC, merged