MAINT-35382: Fix display of uploaded files cyrillic name from WebDav.
exodev/jcr pull request #71
Opened 2020-11-25 13:07 UTC by mdiha

2020-12-04 17:30 UTC, ahamdi requested changes

2020-12-04 17:30 UTC, ahamdi commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/CollectionResource.java
> +         return new HierarchicalProperty(name, decodeValue(StringUtils.equals(node.getPrimaryNodeType().getName(), NodeTypeUtil.NT_FOLDER) ? node.getProperty(NodeTypeUtil.EXO_TITLE).getString() : nod
- to check if  a node is of a defined type, use node.isNodeType(Nodetype)
- Why should you use another proprty than names for NT_Folders ? isn't it the same for NT_UNSTRUCTRED or NT_FILE ?

2020-12-04 17:30 UTC, ahamdi commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/util/NodeTypeUtil.java
> +   final static public String NT_UNSTRUCTURED = "nt:unstructured";
No need to all those properties as they belong to ECMS and there is no need to add them to JCR

2020-12-07 07:57 UTC, mdiha commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/util/NodeTypeUtil.java
> +   final static public String NT_UNSTRUCTURED = "nt:unstructured";
Okay i will remove them.

2020-12-07 08:00 UTC, mdiha commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/CollectionResource.java
> +         return new HierarchicalProperty(name, decodeValue(StringUtils.equals(node.getPrimaryNodeType().getName(), NodeTypeUtil.NT_FOLDER) ? node.getProperty(NodeTypeUtil.EXO_TITLE).getString() : nod
For NT_Folders names in Cyrillic characters are transliterated so we need to display the title instead.

2020-12-07 17:28 UTC, ahamdi commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/CollectionResource.java
> +         return new HierarchicalProperty(name, decodeValue(StringUtils.equals(node.getPrimaryNodeType().getName(), NodeTypeUtil.NT_FOLDER) ? node.getProperty(NodeTypeUtil.EXO_TITLE).getString() : nod
Use node.isNodeType("nt:folder") instead

2020-12-08 09:39 UTC, mdiha commented on exo.jcr.component.webdav/src/main/java/org/exoplatform/services/jcr/webdav/resource/CollectionResource.java
> +         return new HierarchicalProperty(name, decodeValue(StringUtils.equals(node.getPrimaryNodeType().getName(), NodeTypeUtil.NT_FOLDER) ? node.getProperty(NodeTypeUtil.EXO_TITLE).getString() : nod
Done already

2020-12-08 17:17 UTC, ahamdi approved these changes
LGTM

2020-12-09 08:41 UTC, merged